CXX = cl
CXXFLAGS = /std:c++20 /EHsc /nologo /MT
LIBS = ws2_32.lib
BUILD_DIR = build
TARGETS = $(BUILD_DIR)\client_windows_basic.exe $(BUILD_DIR)\client_windows.exe

all: $(TARGETS)

$(BUILD_DIR)\client_windows_basic.exe: src\client_windows_basic.cpp
	if not exist $(BUILD_DIR) mkdir $(BUILD_DIR)
	$(CXX) $(CXXFLAGS) $** /Fo$(BUILD_DIR)\client_windows_basic.obj /Fe:$@ /link $(LIBS)

$(BUILD_DIR)\client_windows.exe: src\client_windows.cpp
	if not exist $(BUILD_DIR) mkdir $(BUILD_DIR)
	$(CXX) $(CXXFLAGS) $** /Fo$(BUILD_DIR)\client_windows.obj /Fe:$@ /link $(LIBS)

clean:
	del /q $(BUILD_DIR)\*.exe $(BUILD_DIR)\*.obj *.obj 2>nul
